pipeline:
  name: aws-python
  identifier: awspythonfm
  projectIdentifier: GitExperienceDemo
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: dev
        identifier: dev
        description: ""
        type: Deployment
        spec:
          serviceConfig:
            serviceRef: pythonservice
            serviceDefinition:
              spec:
                variables: []
                manifests:
                  - manifest:
                      identifier: awspython
                      type: ServerlessAwsLambda
                      spec:
                        store:
                          type: Github
                          spec:
                            connectorRef: account.fmazlabsgit
                            gitFetchType: Branch
                            paths:
                              - .
                            repoName: ma-sls-aws-python
                            branch: main
                        configOverridePath: serverless.yml
              type: ServerlessAwsLambda
          infrastructure:
            environmentRef: preprod
            infrastructureDefinition:
              type: ServerlessAwsLambda
              spec:
                connectorRef: awsconnectormohantylabs
                stage: <+stage.name>
                region: us-east-1
            allowSimultaneousDeployments: false
          execution:
            steps:
              - step:
                  name: Serverless Aws Lambda Deploy
                  identifier: ServerlessAwsLambdaDeploy
                  type: ServerlessAwsLambdaDeploy
                  timeout: 10m
                  spec:
                    commandOptions: ""
                  failureStrategies: []
            rollbackSteps:
              - step:
                  name: Serverless Aws Lambda Rollback
                  identifier: ServerlessAwsLambdaRollback
                  type: ServerlessAwsLambdaRollback
                  timeout: 10m
                  spec: {}
          serviceDependencies: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
